version: "3"
services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "1499:1499"
    networks:
      - app-network
    environment:
      VITE_APPLICATION_HUB_URL=https://ai-broker.korunaassist.com/fusion/v1/datasheets/dstLr3xUL37tbn2Sud/records
      VITE_BROKER_HUB_URL=https://ai-broker.korunaassist.com/fusion/v1/datasheets/dstuqAhBamoBAzziwt/records
      VITE_APPLICANT_HUB_URL=https://ai-broker.korunaassist.com/fusion/v1/datasheets/dst1vag1MekDBbrzoS/records
      VITE_API_TOKEN=usk5YzjFkoAuRfYFNcPCM0j
      VITE_API_URL=http://localhost:1500/api
      VITE_ALLOWED_NETWORKS=www.ai-broker.ai,localhost

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "1500:1500"
    networks:
      - app-network
    environment: PORT=1500
      SUPABASE_JWT_SECRET=jFjyofunqW7KWHRYttGEDamQR5Ji0KyhEQXFi55Yz+D4l+xoAB3JdKowr5A0SJgQ+7w8afrCuyyK16rfwcbOjA==
      SUPABASE_URL=https://vlerrnqmspoofrturhwc.supabase.co
      SUPABASE_SERVICE_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZsZXJybnFtc3Bvb2ZydHVyaHdjIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc0NzE4NDM2NiwiZXhwIjoyMDYyNzYwMzY2fQ.ILvBkflxLyeax7lyWkyl5-pDX6JgSGsRZ6z19mapI-E
      REGION_API=https://restcountries.com/v3.1/all

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
